spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: root
  security:
    user:
      name: test
      password: test